### ISSUE TITLE
bug Unhandled Exception: PathNotFoundException: Cannot open file, path

### ISSUE THREAD

**Issue by yanashenyang** [SpeedPHP/kv#1]
Restarted application in 283ms.
flutter: Directory: '/Users/shenyang/Library/Developer/CoreSimulator/Devices/D6FD8C7A-BCAF-4F98-B0BE-2940E00AE56E/data/Containers/Data/Application/98BD813F-B863-4CBC-8776-2C2E1F5166A6/Documents'
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathNotFoundException: Cannot open file, path = '/Users/shenyang/Library/Developer/CoreSimulator/Devices/D6FD8C7A-BCAF-4F98-B0BE-2940E00AE56E/data/Containers/Data/Application/98BD813F-B863-4CBC-8776-2C2E1F5166A6/Documents/storage/tmz3hxt24yWvtzh0.json' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
file_impl.dart:675
#1      _File.openSync (dart:io/file_impl.dart:490:5)
file_impl.dart:490
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
file_impl.dart:574
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
file_impl.dart:624
#4      new FileStorage._internal (package:kv/src/file_storage.dart:22:36)
file_storage.dart:22
#5      new FileStorage (package:kv/src/file_storage.dart:15:32)
file_storage.dart:15
#6      KvCache.initIDS (package:ph_cheetah/utensil/kv_cache.dart:16:19)
kv_cache.dart:16
<asynchronous suspension>
#7      _Index0BInitState._initAppConfig (package:ph_cheetah/index_0/index_0_b_init.dart:25:5)
index_0_b_init.dart:25
<asynchronous suspension>

**Comment by speedphp** [comment]
It has been fixed in version 1.0.8, please refer to [998174101f37d1888add4d94eda50ca40adb109d](https://github.com/speedphp/kv/commit/998174101f37d1888add4d94eda50ca40adb109d)
